dist: bionic
language: c++
script: g++ -o test.elf test.cpp && ./test.elf
addons:
  coverity_scan:
    project:
      name: gbarc80/fork_test_prv
      version: 1.0
      description: testproject
    build_command: g++ -o test.elf test.cpp
    branch_pattern: coverity_scan
