dist: bionic
language: c++
script: g++ -o test.elf test.cpp && ./test.elf
addons:
  coverity_scan:
    project:
      name: gbarc80/fork_test_prv
      version: 1.0
      description: testproject
    build_command: g++ -o test.elf test.cpp
    branch_pattern: coverity_scan
env:
  global:
    secure: eUTHDUd3e61D+DgWN344MkcTUCPQJvOtJqb57oiFfa+e13wD8U27HOETez3BDHyRKJRu3HPO45OcyRA6c1agLvxaTSMakFdDsKxKiHKo8E6cwlEk6WD8UOVpa7KLzobJ5AfIsAuOx/PHX1Xz2i2eayLue1hWHrrwWwAivducPdHVXKlkamJIpiuBzTW/bRVlkN0dcOD1qMkVRH6WAYRTU5WrEru3A+wqg6+jmeUpzQuWuVumaQajiVenLwpybxqzeO+z7i6D7wL0zVyYbwbZQ3x2+7GdIsqZnxQmhehdl8pmlG/+UbiOuVkkOs97L0O2zrnj001yeamhhhzKWJhbVsLjznIoUEcdx0wPJtenxt6ingjQQh9GGrckdXE68z1aIx48t1VNpHiZ5oyokQ7r640QDa7SBCEjGYjqlDFHioDkfjvCjCo7utynZhPljYQ/sz8rEXsbPlby39J8cK41E7YzazB6ak45C6FaqsGjCaXMXlM0Gmz87VVcWC/NaVXUZ4W1naX6czaGl236XSoA4oc8rjSeB9mADsN/Zi8lpRd3z9yA6z7TlFNt3I0lIbs0kQUXhQYsaqx/lRogHKiRzxpkVucDpSTfdSF2m0ChOGaNcewbugWacBETE4EPWvtsQPHsgT59pp1+HePFqHeyfiqzv+oel3hpEK+Z8L6Lgpw=
